# Constants
COURSERA_DATASET_PATH = "../Dataset/coursera_data.csv"

COURSERA_DATASET_AFTER_CLEANING = "../Dataset/coursera_data_processed.csv"

ORGANIZATION_COUNTRY_MAPPING = {
    # USA - Universities and Colleges
    "Stanford University": "USA",
    "University of Michigan": "USA",
    "Yale University": "USA",
    "Duke University": "USA",
    "University of Pennsylvania": "USA",
    "Johns Hopkins University": "USA",
    "Rice University": "USA",
    "University of Virginia": "USA",
    "University of Washington": "USA",
    "Northwestern University": "USA",
    "University of Illinois at Urbana-Champaign": "USA",
    "Columbia University": "USA",
    "University of California San Diego": "USA",
    "University of California, Davis": "USA",
    "University of California, Irvine": "USA",
    "University of California, Santa Cruz": "USA",
    "University at Buffalo": "USA",
    "University of Colorado Boulder": "USA",
    "University of Colorado System": "USA",
    "Georgia Institute of Technology": "USA",
    "Michigan State University": "USA",
    "Case Western Reserve University": "USA",
    "Vanderbilt University": "USA",
    "University of Minnesota": "USA",
    "The Pennsylvania State University": "USA",
    "Emory University": "USA",
    "New York University": "USA",
    "West Virginia University": "USA",
    "Wesleyan University": "USA",
    "University of Florida": "USA",
    "The State University of New York": "USA",
    "Arizona State University": "USA",
    "University of Maryland, College Park": "USA",
    "California Institute of the Arts": "USA",
    "The University of North Carolina at Chapel Hill": "USA",
    "The University of Chicago": "USA",
    "Rutgers the State University of New Jersey": "USA",
    "McMaster University": "Canada",
    "University of Toronto": "Canada",
    "University of Alberta": "Canada",
    "University of British Columbia": "Canada",
    # USA - Companies and Organizations
    "Google": "USA",
    "Google Cloud": "USA",
    "IBM": "USA",
    "deeplearning.ai": "USA",
    "Amazon Web Services": "USA",
    "Microsoft": "USA",
    "Cisco": "USA",
    "The Museum of Modern Art": "USA",
    "(ISC)²": "USA",
    "Atlassian": "Australia",
    "Unity": "USA",
    "VMware": "USA",
    "HubSpot Academy": "USA",
    "Palo Alto Networks": "USA",
    "SAS": "USA",
    "Autodesk": "USA",
    "Berklee College of Music": "USA",
    "PwC": "UK",
    "BCG": "USA",
    "National Arts Strategies": "USA",
    "Osmosis": "USA",
    "MathWorks": "USA",
    "LearnQuest": "USA",
    "New York Institute of Finance": "USA",
    "Automation Anywhere": "USA",
    "The Linux Foundation": "USA",
    "JetBrains": "Czech Republic",
    "Crece con Google": "Spain",
    "Google - Spectrum Sharing": "USA",
    "E-Learning Development Fund": "Russia",
    "Mail.Ru Group": "Russia",
    "Ticket for Change": "France",
    "American Institute of Business and Economics": "USA",
    "American Museum of Natural History": "USA",
    "Relay Graduate School of Education": "USA",
    "ConsenSys Academy": "USA",
    "Bloomsbury Learning Exchange": "UK",
    "Institute for the Future": "USA",
    "ScrumTrek": "Russia",
    "University System of Georgia": "USA",
    "The George Washington University": "USA",
    "Luther College at the University of Regina": "Canada",
    # UK Universities and Institutions
    "Imperial College London": "UK",
    "University of London": "UK",
    "Goldsmiths, University of London": "UK",
    "The University of Edinburgh": "UK",
    "Birkbeck, University of London": "UK",
    "SOAS University of London": "UK",
    "Royal Holloway, University of London": "UK",
    "UCL Institute of Education": "UK",
    "UCL School of Management": "UK",
    # European Universities and Business Schools
    "INSEAD": "France",
    "HEC Paris": "France",
    "ESSEC Business School": "France",
    "IESE Business School": "Spain",
    "IE Business School": "Spain",
    "IE School of Architecture & Design": "Spain",
    "London Business School": "UK",
    "Copenhagen Business School": "Denmark",
    "Università Bocconi": "Italy",
    "Erasmus University Rotterdam": "Netherlands",
    "University of Amsterdam": "Netherlands",
    "Universiteit Leiden": "Netherlands",
    "Eindhoven University of Technology": "Netherlands",
    "Lund University": "Sweden",
    "Ludwig-Maximilians-Universität München (LMU)": "Germany",
    "Technical University of Denmark (DTU)": "Denmark",
    "École Polytechnique Fédérale de Lausanne": "Switzerland",
    "University of Geneva": "Switzerland",
    "École Polytechnique": "France",
    "École des Ponts ParisTech": "France",
    "Sciences Po": "France",
    "University of Lausanne": "Switzerland",
    "EDHEC Business School": "France",
    "ESCP Business School": "France",
    "ESADE Business and Law School": "Spain",
    "Universitat de Barcelona": "Spain",
    "Universitat Autònoma de Barcelona": "Spain",
    "Saint Petersburg State University": "Russia",
    "National Research University Higher School of Economics": "Russia",
    "Moscow Institute of Physics and Technology": "Russia",
    "Peter the Great St. Petersburg Polytechnic University": "Russia",
    "Novosibirsk State University": "Russia",
    "Kalshoven-Gieskes Forum": "Netherlands",
    "University of Copenhagen": "Denmark",
    # Asian Universities and Institutions
    "The Hong Kong University of Science and Technology": "Hong Kong",
    "The University of Hong Kong": "Hong Kong",
    "Yonsei University": "South Korea",
    "Peking University": "China",
    "Tsinghua University": "China",
    "Shanghai Jiao Tong University": "China",
    "National Taiwan University": "Taiwan",
    "Nanyang Technological University, Singapore": "Singapore",
    "Tel Aviv University": "Israel",
    "Hebrew University of Jerusalem": "Israel",
    "The University of Tokyo": "Japan",
    # Australian Universities
    "Macquarie University": "Australia",
    "The University of Sydney": "Australia",
    "The University of Melbourne": "Australia",
    "University of Cape Town": "South Africa",
    "UNSW Sydney (The University of New South Wales)": "Australia",
    # Latin American Universities
    "Universidad Nacional Autónoma de México": "Mexico",
    "Pontificia Universidad Católica de Chile": "Chile",
    "Universidad de Chile": "Chile",
    "Universidad de los Andes": "Colombia",
    "Universidad Austral": "Argentina",
    "Tecnológico de Monterrey": "Mexico",
    "Universidade de São Paulo": "Brazil",
    "Universidade Estadual de Campinas": "Brazil",
    "Fundação Instituto de Administração": "Brazil",
    # Indian Institutions
    "Indian School of Business": "India",
    # Other Organizations
    "Cloudera": "USA",
    "Icahn School of Medicine at Mount Sinai": "USA",
    "University of New Mexico": "USA",
}

# Country to ISO Alpha-3 mapping for Plotly
COUNTRY_TO_ISO = {
    "USA": "USA",
    "Canada": "CAN",
    "UK": "GBR",
    "Germany": "DEU",
    "France": "FRA",
    "Switzerland": "CHE",
    "Spain": "ESP",
    "Denmark": "DNK",
    "Italy": "ITA",
    "Netherlands": "NLD",
    "Sweden": "SWE",
    "Russia": "RUS",
    "Hong Kong": "HKG",
    "South Korea": "KOR",
    "China": "CHN",
    "Taiwan": "TWN",
    "Singapore": "SGP",
    "Israel": "ISR",
    "Japan": "JPN",
    "India": "IND",
    "Australia": "AUS",
    "South Africa": "ZAF",
    "Mexico": "MEX",
    "Chile": "CHL",
    "Colombia": "COL",
    "Argentina": "ARG",
    "Brazil": "BRA",
    "Czech Republic": "CZE",
}

# Continent mapping
COUNTRY_TO_CONTINENT = {
    "USA": "North America",
    "Canada": "North America",
    "Mexico": "North America",
    "UK": "Europe",
    "Germany": "Europe",
    "France": "Europe",
    "Switzerland": "Europe",
    "Spain": "Europe",
    "Denmark": "Europe",
    "Italy": "Europe",
    "Netherlands": "Europe",
    "Sweden": "Europe",
    "Russia": "Europe",
    "Czech Republic": "Europe",
    "Hong Kong": "Asia",
    "South Korea": "Asia",
    "China": "Asia",
    "Taiwan": "Asia",
    "Singapore": "Asia",
    "Israel": "Asia",
    "Japan": "Asia",
    "India": "Asia",
    "Australia": "Oceania",
    "South Africa": "Africa",
    "Chile": "South America",
    "Colombia": "South America",
    "Argentina": "South America",
    "Brazil": "South America",
}
